### PR TITLE
Add EAN-8 to the list of supported bar codes

### PR DESCRIPTION
**Pull request by henryk**
These are the trivial changes to add EAN-8 (my video rental store uses that) to the list of supported bar codes.

### CODE REVIEW

**Comment by unlobito** [comment]
Thanks for the pull request!

I'm trying it out myself and am having trouble getting the barcodes to scan.
Were you able to successfully scan a EAN-8 barcode from your phone?

**Comment by henryk** [comment]
No, I was chalking that up to focus issues and was hoping the scanner at the shop would work, but wasn't there yet to test.

I have also experimented with better scaling, e.g. allowing all bar codes to scale as long as it's by an integral factor. This would make the EAN-8 (scaled 2x) fit exactly in the display and allowed me to scan it with my phone – though not on the first attempt, I'm chalking that up to the black screen bezel interfering with detection. A better permanent solution would be to rotate the display by 90° for linear bar codes, taking advantage of the slightly larger x screen estate.
I ultimately aborted the attempt (didn't have more time yesterday) because the pebble app also seems to do some scaling which I didn't fully understand.

**Comment by henryk** [comment]
Ok, it's a problem on the watchapp, I believe: the right side seems to be overdrawn, erasing the end markers. While experimenting I had one complete code that scanned without problems, but it got cropped a couple seconds later while switching pages and I haven't been able to reproduce that again.

**Comment by henryk** [comment]
Ok, my last comment was almost right: The problem was that xbi.rb didn't correctly pad the string to a multiple of 8.

**Comment by unlobito** [comment]
That would explain it! Thanks again for your contribution, I've merged your code in and have pushed it to production.

The scaling going on in-app (which is disabled for linear barcodes) simply draws each pixel four times.
I disabled this for linear barcodes since the barcode would frequently exceed the maximum width.

In 3445966, I modified to_xbi to use a larger fixed height for all the linear barcodes.
This should make scanning them a bit nicer until I figure out what to do with [henriwatson/skunk#8](https://github.com/henriwatson/skunk/issues/8)

**Pull request merged**
